### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by runk** [HyeonuPark/randomness#1]
Hello,

I came across this name in npm while looking for a package name for lib for randomness tests. Do you have plans to use this repo and npm module? Thought if you'd consider to remove it from npm so it can be taken.

Thanks!

**Comment by HyeonuPark** [comment]
Sorry for the late reply. Yeah I've unpublished it from the npm. Feel free to occupy it.

**Comment by runk** [comment]
Thanks mate!
